# Config file for automatic testing at travis-ci.org
sudo: true  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
env:
- export FLASK_APP="$TRAVIS_BUILD_DIR/run.py"
- export MYSQL_DATABASE=talkcode
- export MYSQL_PASSWORD=""
- export MYSQL_USER=travis
- export REDIS_URL=redis://:@localhost:6379/0
- export SECRET_KEY=123456789
- export SQLALCHEMY_DATABASE_URI=mysql://travis@localhost/talkcode?charset=utf8&use_unicode=0
python:
  - 2.7
install: pip install -r requirements.txt
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS talkcode;'
script: flask test