# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS talkcode;'
install: pip install -r requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/run.py"
  - export SECRET_KEY=123456789
  - export FLASK_DEBUG=1
script: flask test