# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
env:
- export FLASK_APP="$TRAVIS_BUILD_DIR/run.py"
python:
  - 2.7
install: pip install -r requirements.txt
script: flask test